# Macro file for the initialization of example B4
# in interactive session
#
# Set some default verbose
#
#/control/verbose 2
/control/verbose 0
/control/saveHistory
#/run/verbose 2
/run/verbose 0
/process/em/verbose 0
/process/had/verbose 0
/material/verbose 0
/cuts/verbose 0
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute vis.mac
